language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
  - echo "before_script start"
  - git --version
  - mvn -version
  - ls
  - pwd
  - echo "before_script end"
env:
  global:
    secure: "byBxNFiE3nGQm8JtmrmyC1MQ8mQztK1FYy0cFk26fUbeX47Ore5C8oo8r1prGLPc3PtZuM0fmOtOeg+GVyVOb7veMwsdOdObwxwybzmWCcNJ/bLxFj6KCaYmXOONTMjpldKZCDhgeS9Ffq+vzenUoglm2wLVZ+n8CrCn3n2v5fj8tMWHcPTrC7L5JIP+scyepTFNg91gFvUeVXKuxvtFiPht+uX2thta7B7ZdUnGl0QmGfsLM4paWo1xJ/gwsI5OZ+lugr1lZzENo4ITrwBzyB7TtQxBDH/i9O0hZrELzZoWa31XdXjzSbEkT4fVGibfpkI2CS5W1Cnfch98kkmH2X+IyQtseCpOrAIdcF8NzwnKa4UACH0xIWLn9CVvtyuK1HkZklW1SdxM7PeTgjjbS1jiCM+37PnDr5ZW6vFSNKelvk4Xo7DpomrJCc7I9OuF8FOIItORRRZI4fGXqu4bMjybhWFUMervZW6qrn1ZGRm6gpPcwDPZ7dkL4Qi+TO02a9QKcxrMDM3sngJwTxfY6/dJBtlpZpppnJxp+xHu6rn+3hFeECfvniIDgK1JvpE9+lRL49yZ7Csuj+ag5J9b0gfGvcXjP4qheTf2PsLuC9MqsZvRHs97zSFnGIaun2UhrPYwSUElVyCmCDY7apYpOy/EzX6xG+3FVqN2P55jQa8="
script:
  - echo "script start"
  - ls
  - pwd
  - ls -ltr /home/travis/.m2/
  - rm -rf /home/travis/.m2/
  - echo "### RUN mvn clean"
  - mvn clean -X -e
  - echo "### RUN mvn deploy"
  - mvn deploy -Dpassword=$pass -DuserName=$user -X -e
  - echo "script end"
after_script:
  - echo "after_script start"
  - ls
  - pwd
  - echo "after_script end"
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"

