language: java
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
before_script:
  - echo "before_script start"
  - git --version
  - mvn -version
  - ls
  - pwd
  - echo "before_script end"
env:
  global:
    secure: "PatNGIInARQR/dW1Ud2BgxOY+0bqhfB4Pl8BJNj8DBDCmENqhqVa/+irBmK4BQVD2BDW12daP8rBCVoCHLcA1PlsIuzu+/HXP3Nw6Zp1LxXBrU5hfxjOLM7y6soL2A3myx9dXxWu/K26shTkcwIUJKWp91NFqKLL831qRuisV56WOMmXuV9YPf+DKKYZ3OUtaTWkEu1H5/3WzBu7orVcvt23EQNWdIRg1KNuKieOiJVvkqrXmiwijPxHIifOebU7egkI61eEpGF5y8/Bvkn/fWBmrhS9Wh9wvaN+vkRRdrnSx7OT+TAJ4qUf1j5VamJFdwNCifXW9zhee7c3R5D5OfO6YajqsxCARta0x82+bBtsGvQidllPsEmxMEQwn5fAZP2kI7cp+ZNCwV/m/E3hoTlAWAZ0QOBqTTfP+Ox17ny+PD1UBN2TLKblBOmrONfMBUgUDjcOkpfnclThyH69kzzitEXaKYIiWC2pAo4mmDGdIV57jjoqiHGO50h1q6cw7wNli3zeqBifU5VvsN+k3r7tNf/2gd9sLv8PwSetFQxnfgc5Po/11qPM8V2LvJZtHSJzaa+AdjF6/aMefh7Mb5EIwaaIb3z9AXUvGGXYCMSq7Pu2+dXehoZKIJyalKZ9D6LOGX+KAhlcqVW+C82TrHH1RNd6/KThds8DVRKion8="
script:
  - echo "script start"
  - ls
  - pwd
  - mvn compile
  - echo "secure=$secure
  - echo "SOMEVAR=$SOMEVAR
  - echo "script end"
after_script:
  - echo "after_script start"
  - ls
  - pwd
  - echo "after_script end"
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"
