language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
  - echo "before_script start"
  - git --version
  - mvn -version
  - ls
  - pwd
  - echo "before_script end"
env:
  global:
    secure: "XiVeH/aVn7ZThhWOP5Akv2dEyFnV7iAFBL+KcM+9RuH+H+sddh0Qu0AtcUqn625KhOeCv/qgIFa237dxrFkSMwEX9Bkwb6rLYNDUMbFW+c1Iv1J2+89AKBaccml59TxfUYltVzzeLSEnqgb6TPmjlKk+zccTQr36VDe8BX3SAb08UEcWtXri6REjjopONjezdKRo9BQgL7xK7MABgiK4QZFEUH54bVCgqNGv+ftkhHRstMYXnpblG5vFPC1piFPsqEtECPhTOF5sMFagC15lzGjvRlKulENsfoF3ZOvF3/u6qE6KpCYx8JTKLmF+ZvcOsx6k3mGuIOCaqStd3k45cwefppAk1dYGSwSk+PpMsUVKISwaJVP3cvt76/ScS6w0la2KsI+/2rfIo9QGxAcl3jmwRUgRGC3o025iYWxmZFuRdyUFlzMTVhR8doriGPK21zr7bgboR2GOUfib/ILpUhaGHUNF/rltfpS2xJEoPytBmweXEF4cI2dDm+g9E4p0N7EBvkSImETkACqO3vcUM1j4M3VAvNcyZccmsmmGTgZuGTZWIuIQJYdYZgPO/E16B0OnQVMIeW5PGy4nQc6rITvrwYLQR+s2T6PMbrUn6xxsr7Yu5OEHj/l1iwIS78rTVRbRpNfLPsm6otnDk9OtC4uAJC7NNcbO7EMQ+qgbZyg="
script:
  - echo "script start"
  - ls
  - pwd
  - mvn deploy
  - echo "script end"
after_script:
  - echo "after_script start"
  - ls
  - pwd
  - echo "after_script end"
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"
