language: java
jdk:
  - openjdk6
  - openjdk7
  - openjdk8
before_script:
  - echo "before_script start"
  - ls
  - pwd
  - mvn compile
  - echo "before_script end"
script:
  - echo "script start"
  - ls
  - pwd
  - mvn compile
  - echo "script end"
